//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimento
    {
        public int MovimentoId { get; set; }
        public int AcaoId { get; set; }
        public System.DateTime Data { get; set; }
        public int Qnt { get; set; }
        public float Valor { get; set; }
        public float Lucro { get; set; }
        public bool Visible { get; set; }
    
        public virtual Acao Acao { get; set; }
    }
}
